/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_fs_nrfs_RawFileSystem */

#ifndef _Included_org_apache_hadoop_fs_nrfs_RawFileSystem
#define _Included_org_apache_hadoop_fs_nrfs_RawFileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsConnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsConnect
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsDisconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsOpenFile
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsOpenFile
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsCloseFile
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsCloseFile
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsMknod
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsMknod
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsAccess
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsAccess
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsGetAttibute
 * Signature: ([B[I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsGetAttibute
  (JNIEnv *, jobject, jbyteArray, jintArray);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsWrite
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsWrite
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsRead
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsRead
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsCreateDirectory
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsCreateDirectory
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsDelete
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsDelete
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsRename
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsRename
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_apache_hadoop_fs_nrfs_RawFileSystem
 * Method:    nrfsListDirectory
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_fs_nrfs_RawFileSystem_nrfsListDirectory
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
